### ISSUE TITLE
Deliver Container Image

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thoth-toolbox#8]
Hey, Kebechet!

Please build and deliver the following git tag:

Tag: v0.5.13

**Comment by goern** [comment]
hmmm... this is stale?!

**Comment by harshad16** [comment]
not stale, the issue is building a fedora container that has fastext installation requiring gcc support on a ubi based system image.
l will work on this and try to fix this.

**Comment by fridex** [comment]
@harshad16 should this be closed? thanks 👍🏻
